### ISSUE TITLE
New bug reported - Eric Huber

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#143]
Submitter: Eric Huber
Email: me@erichuber.com
Loving the simplicity! Took me a while to find the master word count, but now that I know...

I've had a few "Disconnected from the Internet" warnings today. Not as bothersome as Google Docs hanging for minutes at time, mind you. A HUGE improvement. AND...I noticed that copying and pasting into Novlr has the paragraph spacing. It actually seemed to appear mid transfer last night. BRAVO!

I was going to include screen shots of when I lost connection, but here's the gist of what I noticed:

Running Chrome on MacBook (white) OS 10.6.8
Had one other window open listening to YouTube music.
2nd-4th time, had Google Doc open as well (for character reference materials)

Result was that i did NOT lose but, maybe, one word upon refresh. However, it took me to the top of the first chapter each time. From there I had to scroll back down to the chapter I was working on, and then scroll to the bottom.

Like I said, not NEARLY as irritating as Google Docs, but I thought you'd want to know.

Thanks much!

Sincerely,
Eric Huber

**Comment by thomasmuirhead** [comment]
replied
