### ISSUE TITLE
New bug reported - Maria Johnson

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#156]
Submitter: Maria Johnson
Email: maria7627@hotmail.com
It would be good if there was a ruler, so we could set an indent rather than having to do it manually via tabs. If we do it via tabs and export, then we would have to go along behind removing all the tab marks and doing a normal indent to clean the manuscript up enough for publishing.

**Comment by thomasmuirhead** [comment]
replied. Indenting feature request
