### ISSUE TITLE
New bug reported - Wendy Thomas

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#157]
Submitter: Wendy Thomas
Email: wethomas@gmail.com
When I try to BOLD a section title, I am brought back up to the top of the chapter start page. A bit problematic when I bold something deep in a document.

**Comment by thomasmuirhead** [comment]
Asked for supportdetails.net. Can't replicate

**Comment by thomasmuirhead** [comment]
No reply from Wendy in two months - closing ticket
