### ISSUE TITLE
New bug reported - Stephanie Ewing

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#159]
Submitter: Stephanie Ewing
Email: ewing.sn@gmail.com
When going to the beta login page for the first-time sign-in using IE 9, Windows 7, there is no guidance in the text-entry fields (leaving the user no idea what to put in which field).  When I used Chrome, I could see the text ("email", "first name", "last name") just fine. 

I realize this might just be caused by using an out-of-date browser, but thought you might want to know. Thanks!!

**Comment by thomasmuirhead** [comment]
Replied and thanked
