### ISSUE TITLE
New bug reported - Rachel

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#160]
Submitter: Rachel
Email: rachelmo90@comcast.net
Copy-pasted text from an email; Novlr spell-check underlined all contractions, eg "couldn't", "won't" until the apostrophe was manually retyped.

**Comment by Novlr** [comment]
Ah I see so some weird apostrophe not being recognised thing! this is good to know. I will add to podio - cc me into the reply please so I do it

**Comment by thomasmuirhead** [comment]
Replied and cc'd Kim in
