### ISSUE TITLE
New bug reported - Mary Garcia

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#161]
Submitter: Mary Garcia
Email: marygarcia@email.com
Followed the directions. Created a new chapter. Added a three line synopsis of what was going to be there. Saw saved at the bottom. But when I clicked to chapter one, then came back to chapter two - all of the words were gone. Tried it a second time and the same thing happened.

**Comment by thomasmuirhead** [comment]
Replied asking for supportdetails.net

**Comment by thomasmuirhead** [comment]
No reply in two months - closing ticket
