### ISSUE TITLE
New bug reported - Laitie

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#165]
Submitter: Laitie
Email: laitiegrl@hotmail.com
So, here's the deal. I already have a novel in progress. So I'm trying to copy and paste it into this program. I'm already a little under 30,000 words in, so I have a lot of copying and pasting to do. It looks like formatting is going to be a pain in the neck. Now, this may be because I'm copying from Open Office which is copying from Zen Writer, but maybe not.

OK, so, I'll copy the whole chapter, right? Paste it in, and Novlr seems to have decided to take the first 1-3 words of each paragraph and make it/them its/their own line. I only glanced through the chapter before giving up and ex-ing out, but I'm pretty sure this was true for each and every paragraph.

I dunno if you're even interested in how your word processor takes care of copying and pasting, just thought maybe I'd try to help out just in case, y'know? Thanks!

**Comment by thomasmuirhead** [comment]
Replied. Duplicate pasting issues.
