### ISSUE TITLE
New bug reported - Lois

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#166]
Submitter: Lois
Email: LMEighmy@gmail.com
I just got the beta invite. I filled out the info, but it won't let me log in. It says my email address is invalid.

Email address: LMEighmy@gmail.com
Password: *S&KbjSArWk3

Lois Eighmy

**Comment by thomasmuirhead** [comment]
Replied asking her to try post beta - but will wait to see if she has any other problems.

**Comment by thomasmuirhead** [comment]
No reply in two months - closing ticket
