### ISSUE TITLE
New bug reported - Aaron Crocco

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#169]
Submitter: Aaron Crocco
Email: acrocco@gmail.com
My internet was lost while writing and I received the popup notification to get reconnected. This is great but the popup doesn't allow me to 'rescue' my writing via copy & paste so I can offload it into Notes or any other text editor. Luckily I got reconnected and my work had been 99% saved, but the ability to get my writing when losing my connection in order to save a local copy would be a big UI improvement.

iPad Air 1, iOS 8.1, Safari.

**Comment by thomasmuirhead** [comment]
Replied - internet connectivity.
