### ISSUE TITLE
New bug reported - Jaime Cooper

### ISSUE THREAD

**Issue by ghost** [Novlr/novlr-beta#170]
Submitter: Jaime Cooper
Email: jaime.cooper@purenyxdesign.com
It would be awesome to have a section dedicated to the novel summary/blurb that isn't categorized as a chapter so as to not throw off the chapter numbers. It could have a collapsible label just under the novel title and above Chapter 1, for a placement idea.

**Comment by thomasmuirhead** [comment]
Feature request - notes should cover it. replied
