### ISSUE TITLE
Mishell Baker - beta link not working

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#173]
Submitter: Mishell Baker
Email: mishellbaker@gmail.com
Well, my first report is that I can't even get to the beta.  I clicked the link in the email and got this: Cannot GET /signup/lEAFhI9uyPv7VGc3?utm_source=Novlrists&utm_campaign=9c4c850a90-B022&utm_medium=email&utm_term=0_b5d5549fed-9c4c850a90-144754533

**Comment by thomasmuirhead** [comment]
Replied and apologised
