### ISSUE TITLE
Malik M.L. Williams feature request settings automatic close

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#176]
Submitter: Malik M.L. Williams
Email: malikmlwilliams@gmail.com
Not so much a bug (i think) as a suggestion:

Using Safari 8.0 on Mac OS X Yosemite 10.10, i click on the Settings menu and get the dropdown. I click back in the text of my chapter and the dropdown menu does not retract automatically as i expected; i had to click on Settings again. I'd offer the suggestion to have it retract in the same way browser menus do if the user clicks anywhere other than one of the dropdown menu options.

**Comment by thomasmuirhead** [comment]
Replied and thanked him.
