### ISSUE TITLE
Chelle - lost work

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#179]
Submitter: Chelle
Email: whosthatchelle@gmail.com
My first chapter has completely disappeared. I was going to use your program to write my NaNoWriMo. I had 1716 words in my first chapter. Now when  I log in, it's all gone.

**Comment by Novlr** [comment]
Hi Chelle, 

I'm really sorry you've been having trouble.

At the moment if you work on multiple devices, when you switch you need to make sure you refresh the page to get the latest changes. We have had a couple of reports of this not being enough to update and that clearing the cache does. It's important in this situation not to write into the editor if it looks like an older version as it will overwrite. We are currently building a solution to this that will go live in the next few weeks.

If refreshing the page didn't update it - did you lose any words? Are they back now? If they aren't there, let me know what time you know they were there (ie a time after you finished editing them and before you noticed the older one) and I will have a look at our backups and see what I can to get them back for you. 

We have tried to make beta as stable as possible but these issues are the reason we have such a long beta testing period to make sure when we launch a full release it is as stable as it can be. As I say, we are working on a way to make sure you never have to think about whether the latest changes are there no matter how many devices you have it open on - and that will go live very soon.

Thanks, 
Kim
Novlr

**Comment by Novlr** [comment]
This was a week ago so even though I haven't had a response yet I have saved the backups from 15 minutes before she reported the bug, 25 minutes before, 35 minutes before and 2 hours before

**Comment by thomasmuirhead** [comment]
No response for over two months
