### ISSUE TITLE
Macario Reyes - lost work

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#180]
Submitter: Macario Reyes
Email: mister.eyes@gmail.com
OS -  Ubuntu
Browser - Firefox for Ubunutu 33.0

Upon closing the browser, all text is lost. Regardless of the status reported by the "Saved" indicator on the bottom bar, there is no text when you sign back on to the site. Signing out or closing the browser seems to make no difference.

**Comment by Novlr** [comment]
Hi Macario, 

I'm really sorry you've been having trouble.

At the moment we are seeing problems with working on multiple devices - meaning when you switch, you need to make sure you refresh the page to get the latest changes. We have had a couple of reports of this not being enough to update and that clearing the cache does. (It's important in this situation not to write into the editor if it looks like an older version as it will overwrite). We are currently building a solution to this that will go live in the next few weeks.

However, it sounds like in your case, you are on the same device and you can't get your words to load. It is possible this could be a ubuntu issue as we have very few beta testers on ubuntu meaning there are likely to be more issues. I'll look into this too in case it is a slightly separate issue to the one I describe above.

If refreshing the page didn't update it - did you lose any words? Could you try clearing the cache? If you lost words, let me know what time you know they were there (ie a time after you finished editing them and before you noticed the older one), I will have a look at our backups and see if they are actually saving properly, and if you've lost them, what I can do to get them back for you.

As I say we are working on a way to make sure you never have to think about whether the latest changes are there no matter how many devices you have it open on that will go live very soon.

Thanks, 
Kim
Novlr

**Comment by thomasmuirhead** [comment]
No response for two months
