### ISSUE TITLE
Ebone - lost work on different devices

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#182]
Submitter: ebone
Email: echerie82@hotmail.com
Used Safari on Ipad, but work isn't updated when logged into chrome on laptop. On the ipad I have 1225 words and 3 chapters, but on the desktop only 517 and 1 chapter. I've used both ipad and standard desktop together and not had this issue before.

**Comment by thomasmuirhead** [comment]
Just sent sorry for not getting in touch email to her.
