### ISSUE TITLE
Tina Kirby - popping to top of page issue

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#183]
Submitter: Tina Kirby
Email: tina.kirby@swangen.co.uk
I've just been going through editing some grammatical errors when I noticed that the page keeps popping to the top of the page rather than stay where it was.   This got annoying after a while and made me wonder if it had adjusted the wrong part of the chapter.

**Comment by thomasmuirhead** [comment]
Replied asking some questions

**Comment by thomasmuirhead** [comment]
No response in months
