### ISSUE TITLE
Angela - handwriting keyboard issues

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#184]
Submitter: Angela
Email: angela.craft@gmail.com
I am on Chrome on my Samsung Note 2014 edition, using the Samsung native keyboard with handwriting recognition. While using the handwriting recognition, the cursor will randomly jump about, causing me to lose some of what I'very written and/or create pure gibberish if I'm not constantly monitoring where the cursor has ended up. Novlr looks great, but if it can't handle the handwriting keyboard, it's not the tool for me.

**Comment by thomasmuirhead** [comment]
Replied
