### ISSUE TITLE
Stephen - strange bug needs more info

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#185]
Submitter: Stephen
Email: stephen@stephenthewriter.com
I logged in to attempt to work on my novel and when I login it's blank, when I click chapter 1 it stays blank, if I click chapter 2 my first chapter is visible and if I click on chapter 3 that is also blank.

**Comment by thomasmuirhead** [comment]
Replied asking for more information

**Comment by thomasmuirhead** [comment]
Reply from Stephen 11/11 

I've had the issue on windows xp and windows 7 using chrome and on windows 7 using internet explorer at times when you type the screen keeps scrolling back to the top with every keystroke.
