### ISSUE TITLE
Christian Cook - pasting issues

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#190]
Submitter: Christian Cook
Email: shout@christiancook.com
I am using Chrome 38.0.2125.111 on Mac OS 10.7.5. Pasting straight from Word 12.3.6 throws all the line breaks out and causes strange formatting issues. Pasting into a text doc and out again is a workaround, but transferring a 37 chapter novel across would be quicker if I could go straight from Word.

**Comment by thomasmuirhead** [comment]
Replied.
