### ISSUE TITLE
Jess - Safari issues

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#191]
Submitter: Jess
Email: jessicajasch@gmail.com
I'm using Safari on Mac and unable to see the formatting options. However, when I hover the cursor over where they should be, it changes as if there's something there to click on. I just can't see what it is.
Another thing I noticed on Safari/Mac, is if the window is stretched across the screen too long (but to fit the screen like normal) a horizontal scroll bar appears and the whole Novlr view isn't available. This occurs still when reducing the width (at some point in the middle losing the horizontal scroll but the text across is still cut off) until all of the text realigns to a new, narrower column.

**Comment by thomasmuirhead** [comment]
Replied to the lovely @jessjasch
