### ISSUE TITLE
Lauryn - lost internet connection

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#193]
Submitter: Lauryn Anderson
Email: laurynsnotebook@hotmail.co.uk
Despite having a full internet connection an error message occurred stating that I had lost the internet. I am using Google Chrome and Microsoft Windows Vista. Thanks!

**Comment by thomasmuirhead** [comment]
Hi Lauryn

I'm sorry we seemed to miss this ticket - sorry for the delay. The lost connection issue is one we're aware of and are trying to sort it out by building the functionality that lets you go offline. (It's frustratingly complicated!) Sorry it's taking us so long.

Are you still using Novlr? How's your writing going?

Thomas
