### ISSUE TITLE
Jennifer Lee - lost work

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#194]
Submitter: Jennifer Lee
Email: jjesunlee@gmail.com
I was working on two different computers, and one computer shows an older version. If they are synced online, shouldn't they be the same? Now I am afraid that novlr is not really saving my work in the cloud.

**Comment by childdotorg** [comment]
Hi Jennifer, 

I'm really sorry you've been having trouble.

At the moment if you work on one device then move to another, then back to the original you need to make sure you refresh the page to get the latest changes. We have had a couple of reports of this not being enough to update and that clearing the cache does. It's important in this situation not to write into the editor if it looks like an older version as it will overwrite. We are currently building a solution to this that will go live in the next few weeks.

If refreshing the page didn't update it - did you lose any words? If you did and let me know what time you know they were there (ie a time after you finished editing them and before you noticed the older one), I will have a look at our backups and see what I can to get them back for you.

As I sat we are working on a way to make sure you never have to think about whether the latest changes are there no matter how many devices you have it open on that will go live very soon.

Thanks, 
Kim
Novlr

**Comment by thomasmuirhead** [comment]
No repsonse in two months
