### ISSUE TITLE
Kasey Rackowitz - lost work

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#195]
Submitter: Kasey Rackowitz
Email: krackowi@uw.edu
I just logged back into the computer version of Novlr and none of my writing is there. Chapter 1 has the title still, but it's a blank document. When I logged into the mobile page, all my writing is there. I'm typing all of that back onto the chapter on the computer page and see what happens from there.

**Comment by Novlr** [comment]
Hi Kasey,

I'm really sorry you've been having trouble.

At the moment if you work on one device then move to another, then back to the original you need to make sure you refresh the page to get the latest changes. We have had a couple of reports of this not being enough to update and that clearing the cache does. It's important in this situation not to write into the editor if it looks like an older version as it will overwrite. We are currently building a solution to this that will go live in the next few weeks.

If refreshing the page didn't update it - did you lose any words? If you did and let me know what time you know they were there (ie a time after you finished editing them and before you noticed the older one), I will have a look at our backups and see what I can to get them back for you, although it sounds like you manually took that into your own hands which is admirable but for which I am so sorry. You shouldn't have had to do that. We have tried to make beta as stable as possible but these issues are the reason we have such a long beta testing period to make sure when we launch a full release it is as stable as it can be. 

Like I say, let me know if I can try and retrieve your words and I'll do whatever I can.
Thanks,
Kim

**Comment by thomasmuirhead** [comment]
No response in two months
