### ISSUE TITLE
Rafi - lost connection issue

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#196]
Submitter: Rafi
Email: oamealkid@gmail.com
It keeps losing internet connection

**Comment by thomasmuirhead** [comment]
Hi Rafi

I'm sorry we seemed to miss this ticket - sorry for the delay. The lost connection issue is one we're aware of and are trying to sort it out by building the functionality that lets you go offline. (It's frustratingly complicated!) Sorry it's taking us so long.

Are you still using Novlr? How's your writing going?

Thomas

PS: Happy 2015!
