### ISSUE TITLE
Trudi Larkworthy - lost work

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#197]
Submitter: Trudi Larkworthy
Email: truudes@gmail.com
I wrote around 600 words last night on my phone. In total, I had 9,620 words. I logged on my laptop today and I checked the total, which said 9,620. I went to my most recent chapter to continue writing, but it left off where I finished on my laptop, not my phone. I checked the word count again, and it had gone back down to 8,991. I do back up my work on Evernote, but with it being on my phone I, planned to do it now, on my laptop. I can remember vaguely what I wrote and what happened, but I'm not happy that my work was saved and then disappeared. If I wasn't participating in NaNoWriMo, I wouldn't have the patience to even bother rewriting all of that. If it is saved somewhere and it just hasn't been retrieved, then I hope that can be fixed. Otherwise I will have to write it again. I hope this doesn't happen again, because I do really like using Novlr. It's simply designed and easy to use.

**Comment by Novlr** [comment]
Hi Trudi, 

I'm really sorry you've been having trouble.

At the moment if you work on one device then move to another, then back to the original you need to make sure you refresh the page to get the latest changes. We have had a couple of reports of this not being enough to update and that clearing the cache does. It's important in this situation not to write into the editor if it looks like an older version as it will overwrite. We are currently building a solution to this that will go live in the next few weeks.

If refreshing the page didn't update it - did you lose any words? Are they back now? If they aren't there, let me know what time you know they were there (ie a time after you finished editing them and before you noticed the older one) and I will have a look at our backups and see what I can to get them back for you. I do not want you having to re-write them.

We have tried to make beta as stable as possible but these issues are the reason we have such a long beta testing period to make sure when we launch a full release it is as stable as it can be. As I say, we are working on a way to make sure you never have to think about whether the latest changes are there no matter how many devices you have it open on that will go live very soon.

Thanks, 
Kim
Novlr

**Comment by thomasmuirhead** [comment]
No response in two months
