### ISSUE TITLE
Natasha - lost work issue

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#198]
Submitter: Natasha De Vil
Email: natashadevil@ymail.com
Work I typed up yesterday said it was saved but today it is not there.

**Comment by Novlr** [comment]
Hi Natasha,

I'm really sorry for the delay in getting back to you and so sorry you have been having trouble. I'll get to the bottom of the problem and can see if I can retrieve your words.

I am going to have a look into why your editor wouldn't have had the latest version in there, especially since it was the same device. Did you try to refresh the page? It seems sometimes the browser is caching when it shouldn't and I'm looking into that. Either way, I will try and replicate the issue and fix it. It would be really useful if you could tell me which browser and device you were using? Thank you.

Regarding your words, if you let me know at what time you know the words were definitely there (ie sometime after you finished editing and before you came back to it again) I can look in our backups and see if I can get your words back.

I'll do whatever I can to resolve this.

Thanks a lot, 
Kim
Novlr

**Comment by thomasmuirhead** [comment]
No response in two months
