### ISSUE TITLE
Allison Kriumsiek - lost work

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#206]
Submitter: Allison Krumsiek
Email: allisonkrumsiek@gmail.com
When I switch computers, sometimes my work doesn't follow. It automatically saves, so it should be the same no matter where I am, right? I wrote a chapter on one laptop this morning, and on my home laptop it doesn't show, even if I login and out. I sure hope it still exists!

**Comment by Novlr** [comment]
Hi Alison, 

I'm really sorry you've been having trouble.

At the moment if you work on one device then move to another, then back to the original you need to make sure you refresh the page to get the latest changes. We have had a couple of reports of this not being enough to update and that clearing the cache does. It's important in this situation not to write into the editor if it looks like an older version as it will overwrite. We are currently building a solution to this that will go live in the next few weeks.

If refreshing the page didn't update it - did you lose any words? Are they back now? If they aren't there, let me know what time you know they were there (ie a time after you finished editing them and before you noticed the older one) and I will have a look at our backups and see what I can to get them back for you. 

We have tried to make beta as stable as possible but these issues are the reason we have such a long beta testing period to make sure when we launch a full release it is as stable as it can be. As I say, we are working on a way to make sure you never have to think about whether the latest changes are there no matter how many devices you have it open on - and that will go live very soon.

Thanks a lot for your support, 
Kim
Novlr

**Comment by thomasmuirhead** [comment]
No response in two months
