### ISSUE TITLE
New bug reported - Stephanie Ewing - lost work

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#207]
Submitter: Stephanie Ewing
Email: ewing.sn@gmail.com
Hello Novlr team,

When I login with Chrome (version 38.0.2125.111 m) I don't see any of my ~3,000 word story text or word count saved--it's just a blank document with the name of the novel appearing just fine, or, it will revert to a version that is missing a substantial amount of text. I've refreshed multiple times, even on different computers (both PCs) on two different days, but I'm still never quite sure what's going to show up. Luckily, I save a backup because I'm paranoid and this is still in beta, so I'm not stressing. Thanks for your hard work in making this a great way to write!

-Stephanie

**Comment by Novlr** [comment]
Hi Stephanie,

I'm really sorry you've been having trouble.

At the moment if you work on one device then move to another, then back to the original you need to make sure you refresh the page to get the latest changes. We have had a couple of reports of this not being enough to update and that clearing the cache does. It's important in this situation not to write into the editor if it looks like an older version as it will overwrite. We are currently building a solution to this that will go live in the next few weeks.

It is good for you that you backed up, I'm glad you haven't lost any words but once out of beta we want Novlr to be a place you can write without having to do that. Including fixing this problem you describe, and down the line maybe integrated automatic backups with things like google docs or dropbox for the more paranoid :) We do take double backups every 10 minutes and save them for a whole week so if you do ever lose anything, please let me know and I can do what i can to get them back.

We have tried to make beta as stable as possible but these issues are the reason we have such a long beta testing period to make sure when we launch a full release it is as stable as it can be. As I say, we are working on a way to make sure you never have to think about whether the latest changes are there no matter how many devices you have it open on that will go live very soon.

Thanks a lot for your understanding and support, it means a lot to us!
Kim
Novlr

**Comment by thomasmuirhead** [comment]
No response in two months
