### ISSUE TITLE
Lost work - Seth

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#215]
Submitter: Seth
Email: rengare@black-wolfe.net
So this has happened a few times now, and I'm glad I've been backing up my data because of it.

I don't always use the same browser when I type into Novlr.  I usually use a version of Firefox utilizing my work laptop.  Which is fine and dandy.  Every time I work using that application consecutively, I find that all my chapters are complete, and the word count accurate.

If I decide to work from my home Desktop using Google Chrome, I find that the chapters that I've worked on previously have suddenly been altered, back to a state that I believe was a previous rendition that I was typing using Google Chrome before.  I haven't tested this in any other browser, but it seems to be consistent.

However, my latest chapter always seems to be okay, it's just each previous chapter that gets altered.

I can continue attempting to duplicate this issue and report back.

**Comment by thomasmuirhead** [comment]
Had apology reply
