### ISSUE TITLE
Pasting issues - Sabela

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#216]
Submitter: Sabela
Email: sabelagpanizo@gmail.com
Pasting unnecessary line breaks when pasting from Open Office (after first word) > Has happened in Mozilla and Chrome, both Windows 7 and iOS Mavericks.
Unnecessary line breaks have appeared in text when refreshing content (as word count had not updated to the last edit) > Last edits had been done in Windows 7 pasting from Open Office and working online in Mozilla, the issue has been spotted while working in Chrome from an iOS Mavericks.

**Comment by thomasmuirhead** [comment]
Sent apology reply
