### ISSUE TITLE
Lost words - Boyd Jamison

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#218]
Submitter: Boyd Jamison
Email: legendaryboyd@msn.com
Word Count stopped moving randomly but Novlr said it had saved. I reloaded to find that it actually hadn't saved and had returned to where the word count had stopped. I did copy and paste what I'd written so I didn't lose anything but if someone hadn't noticed then this error could have cost them some work. It's probably a complication of the on line system and will be solved when the offline mode in finished.

**Comment by thomasmuirhead** [comment]
Sent apology reply
