### ISSUE TITLE
Eilish - lost all his words

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#222]
Submitter: eilish zenwirth
Email: curiouscharles@outlook.com
i just lost my whole story when it claimed it was saved when in reality it wasnt

**Comment by Novlr** [comment]
Emailed Elish:

Hello Elish,

My name is Ellie and I'm keeping an eye on Novlr for a couple of weeks while Thomas and Kim are away.

Checking the bug reports I saw your report about your story being lost, I'm really sorry to hear this. Would you possibly be able to give me a little more information? If you would like me to, I can get in contact with the web developer and see if I can retrieve the words you have lost.

When you say 'just lost my whole story' could you elucidate slightly for me? Did you log out and then log in on a different computer and find your words were not there? Or did you refresh and find they were gone?

If you would like me to see if the developer can retrieve your words, please could you let me know the last time and date that your words were all there?

Many thanks for trying out Novlr Beta, and I'm sorry this bug has inconvenienced you. Please do let me know if you'd like me to look into this further for you.

Ellie

**Comment by thomasmuirhead** [comment]
No response in two months
