### ISSUE TITLE
Lost first chapter words - return on refresh Barry Cooper

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#224]
Submitter: Barry Cooper
Email: barry.cooper@buddingcottage.co.uk
Hi
Not sure its a bug, but i've just logged back into my account this evening and the whole of my first (and only) chapter is empty.
A bit of a panic. 
I created a second chapter, and added a couple of words and then switched back to chapter one and they all reappeared.

A bit scary.

I'm using Novlr via a Mac book (if that helps).

Regards
Barry

**Comment by thomasmuirhead** [comment]
Sent apology reply
