### ISSUE TITLE
Lost work - Lieke Kessels

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#233]
Submitter: Lieke Kessels
Email: lj.kessels@gmail.com
Safari had an error causing my browser to reboot. When I returned to the Novlr page and went to the Chapter i had been working on the page was blank. So I clicked on the title of the chapter again and still didn't find my work. No worl is lost cause i've backed it up to a word doc, but still want to make a note of it.  

I hope you guys can locate the bug.

Cheers

**Comment by thomasmuirhead** [comment]
Sent apology reply
