### ISSUE TITLE
STrange not showing words on different devices - Meghan

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#240]
Submitter: Meghan
Email: meghan7x@gmail.com
Originally, I worked on my story on my personal computer and on Google Chrome. Recently, I've been working on my 6th chapter it on my schools' computers and on my sister's computer (also using Google Chrome). It's been saving correctly on those two computers.

However, today I logged back on on my personal computer and only part of my 6th chapter showed up. I refreshed the browser, but still only part of the 6th chapter showed up. I signed out of my account and signed back in, but still only part of the 6th chapter showed up..

I logged onto my sister's computer, and the whole 6th chapter showed up. 

Apart from this, I haven't been having any problems with my personal computer. I thought it might be a bug so I figured I would report it.

Also, I sometimes get an error message that novlr can't connect to the internet (on my personal and school computers) even though the internet is working perfectly fine for other sites.

Thank you for taking the time to read this report! I really like the layout of novlr and it's a pleasure to write with. Good luck developing it!

**Comment by thomasmuirhead** [comment]
Sent apology reply
