### ISSUE TITLE
Lost work - Garo Molozian

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#246]
Submitter: Garo Molozian
Email: garo@molozian.co.uk
When I logged in, I got the welcome page. Then clicked on my book title, but cannot access my previous Chapters. I can see the Chapter list momentarily but it disappears quickly, so I cannot for example click on my Chapter 1

**Comment by thomasmuirhead** [comment]
Sent reply asking if still getting issue and asking for more information
