### ISSUE TITLE
Lost work Jessica Smith

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#248]
Submitter: Jessica Smith
Email: j-smith95@live.ca
I used your website a few days ago to do some more writing, logged on today and it was all gone. Luckily, I started my work on celtx.com and only moved to novlr a couple weeks ago to check it out, so I haven't lost much. Needless to say, a website that claims to save your work every two seconds and then loses it all is not one that I need. Thanks for the trial run but I will be going back to celtx.com for the remainder of my novel.

**Comment by thomasmuirhead** [comment]
Wrote to her - a bit of a worry. Waiting for reply.
