### ISSUE TITLE
Delete my account Jessica Smith

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#263]
Submitter: Jessica Smith
Email: j-smith95@live.ca
Hi Novlr staff,

After a few weeks on novlr, I've decided I would like to delete my novlr account. I'm not sure how to do this and didn't know where else to request this. You can delete my account and all writing and data attached to it, as I no longer write on this forum.

Thanks,

Jessica Smith

**Comment by thomasmuirhead** [comment]
Kim to delete and let me know
