### ISSUE TITLE
Jessica Waters - duplicated chapters

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#271]
Submitter: Jessica Waters
Email: imaginary_world@hotmail.com
I opened up my novel and noticed that there were two copies of every chapter. I refreshed the page and then there were four copies of every chapter. Refreshed again and now there are eight copies of every chapter. I'm leaving it at eight since I can see where this pattern is going. This is happening in Chrome web browser. I haven't tried to open it anywhere else since I really don't want to double the number of duplicate chapters again.
Thanks!

**Comment by thomasmuirhead** [comment]
Replied asking:
Thanks for letting us know - that's a real pain. Sorry. It has happened to a couple of other people too and we can revert back to where you were before - so we'll fix it! We're still trying to work out why it is happening. Could I ask a couple of questions:
When did you last work on the novel without it doubling? (we'll need an estimated date and time to pull your last version out)
Have you logged out and in again any time in the last couple of weeks?
Could you go to http://supportdetails.net and send us the link that they give you on the right hand side of the page
Thank you. Sorry about this. Kim isn't around just now, but she'll get on to it as soon as she can and get your old version back.

Thanks for your patience
