### ISSUE TITLE
Jaqueline - Lost Words between chapters

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#281]
Submitter: Jacqueline Moreno
Email: jmoreno@mills.edu
Your Novlr deleted my story!  I almost certain that I did not click the trash icon, and after flipping between chapters, I came back to my chapter called "My Parents" but the content was gone! :-( 

I would really appreciate it if someone helped me to get my story back. I want to cry right now because I worked so hard on it, trusting your product. :-(

**Comment by thomasmuirhead** [comment]
We got her her words. She was happy.
