### ISSUE TITLE
Name change - Kim on it

### ISSUE THREAD

**Issue by Novlr** [Novlr/novlr-beta#336]
Submitter: Alex
Email: alexanderal002@outlook.com
I'm not really reporting a BUG, rather more of an unsolvable issue.

I haven't been on here in awhile, but it would appear that I misspelled my name during signup (it has AleCander, and I'm AleXander, no capitals, just pulling attention to the swapped letter). I went to my settings and was not able to change the spelling. Did I just miss this or is there not a way to change it?

If there isn't a way for me to change it, I'd be super happy if you guys to make that change for me.

My thanks in advance!

-Alexander Bertrand
alexanderal002@outlook.com

**Comment by thomasmuirhead** [comment]
Name changed by Kim
